version: '3'
services:
    movieapi:
        build: 
            context: .
            dockerfile: Dockerfile.prod
        image: movieapi
        container_name: movieapi
        restart: always
        ports:
            - "49160:8080"
        links:
            - moviedb
        depends_on:
            - moviedb
    moviedb:
        image: andresvidal/rpi3-mongodb3:3.0.14
        container_name: moviedb
        # volumes:
        #   - ./data:/data/db
        ports:
            - "27017:27017"