version: '3'
services:
    movieapi:
        build: .
        image: movieapi
        container_name: movieapi
        restart: always
        ports:
            - "49160:8080"
        links:
            - moviedb
        depends_on:
            - moviedb
    moviedb:
        image: mongo
        container_name: moviedb
        # volumes:
        #   - ./data:/data/db
        ports:
            - "27017:27017"